# Generated by Django 5.2.15 on 2026-06-06 15:38

import django.db.models.deletion
import generator.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "sample",
                    models.FileField(upload_to=generator.models.voice_sample_path),
                ),
                ("voice_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cloning", "Cloning voice"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="cloning",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synthesizing", "Synthesizing speech"),
                            ("animating", "Animating"),
                            ("processing", "Finalizing video"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to=generator.models.job_image_path)),
                ("text", models.TextField()),
                ("resolution", models.PositiveIntegerField(default=480)),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to=generator.models.job_audio_path
                    ),
                ),
                (
                    "did_talk_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "result_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="generator.voice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
