# Generated by Django 5.2.15 on 2026-06-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videojob",
            name="voice",
        ),
        migrations.AddField(
            model_name="videojob",
            name="voice_id",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videojob",
            name="voice_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
