# Generated by Django 5.2.15 on 2026-06-06 16:21

import generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_remove_videojob_voice_videojob_voice_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="background_video",
            field=models.FileField(
                blank=True, null=True, upload_to=generator.models.job_bg_video_path
            ),
        ),
        migrations.AddField(
            model_name="videojob",
            name="composite",
            field=models.FileField(
                blank=True, null=True, upload_to=generator.models.job_composite_path
            ),
        ),
        migrations.AddField(
            model_name="videojob",
            name="position",
            field=models.CharField(
                choices=[
                    ("bottom-left", "Bottom left"),
                    ("bottom-center", "Bottom center"),
                    ("bottom-right", "Bottom right"),
                ],
                default="bottom-left",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="videojob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synthesizing", "Synthesizing speech"),
                    ("animating", "Animating"),
                    ("processing", "Finalizing video"),
                    ("compositing", "Compositing overlay"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
