# Generated by Django 5.2.15 on 2026-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_videojob_background_video_videojob_composite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="accent",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="voice",
            name="language",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
