# Generated by Django 5.2.15 on 2026-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0004_voice_accent_voice_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="overlay_diameter",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videojob",
            name="overlay_x",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videojob",
            name="overlay_y",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
