# Generated by Django 5.2.15 on 2026-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0005_videojob_overlay_diameter_videojob_overlay_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="overlay_border",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videojob",
            name="overlay_border_color",
            field=models.CharField(blank=True, default="", max_length=9),
        ),
    ]
