# Generated by Django 5.2.15 on 2026-06-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0006_videojob_overlay_border_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="overlay_keyframes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
