"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-6@=8yr_)uhld16x$wksf5i8&8p@*e!&n8ez*wqb&63g=kehu^3",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "generator",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (user uploads + generated audio)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# --- File storage -------------------------------------------------------
# Store uploads (avatar images, generated audio) on DigitalOcean Spaces
# (S3-compatible) when DO_* creds are present; otherwise fall back to the
# local filesystem for development.
DO_ACCESS_KEY_ID = config("DO_ACCESS_KEY_ID", default="")
DO_SECRET_ACCESS_KEY = config("DO_SECRET_ACCESS_KEY", default="")
DO_BUCKET = config("DO_BUCKET", default="")
DO_DEFAULT_REGION = config("DO_DEFAULT_REGION", default="")
DO_ENDPOINT = config("DO_ENDPOINT", default="")

if DO_ACCESS_KEY_ID and DO_SECRET_ACCESS_KEY and DO_BUCKET and DO_ENDPOINT:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": DO_ACCESS_KEY_ID,
                "secret_key": DO_SECRET_ACCESS_KEY,
                "bucket_name": DO_BUCKET,
                "region_name": DO_DEFAULT_REGION,
                "endpoint_url": DO_ENDPOINT,
                "default_acl": "public-read",
                "querystring_auth": False,
                "file_overwrite": False,
                "location": "vidgen",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- CORS ---------------------------------------------------------------
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
    cast=Csv(),
)


# --- REST framework -----------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
}


# --- Third-party / pipeline config -------------------------------------
ELEVENLABS_API_KEY = config("ELEVENLABS_API_KEY", default="")
DID_API_KEY = config("DID_API_KEY", default="")

# ElevenLabs synthesis defaults
ELEVEN_MODEL_ID = config("ELEVEN_MODEL_ID", default="eleven_multilingual_v2")
ELEVEN_OUTPUT_FORMAT = config("ELEVEN_OUTPUT_FORMAT", default="mp3_44100_128")

# Default output video resolution (longest dimension, px). 480p by default.
DEFAULT_RESOLUTION = config("DEFAULT_RESOLUTION", default=480, cast=int)

# Validation / safety limits
MAX_TEXT_LEN = config("MAX_TEXT_LEN", default=2500, cast=int)
MAX_UPLOAD_MB = config("MAX_UPLOAD_MB", default=25, cast=int)
# Background videos can be larger than image/audio uploads.
MAX_VIDEO_MB = config("MAX_VIDEO_MB", default=200, cast=int)
# D-ID rejects images smaller than 100x100 px.
MIN_IMAGE_DIM = config("MIN_IMAGE_DIM", default=100, cast=int)

# How long to poll the video render before giving up (s) and the poll interval.
VIDEO_POLL_TIMEOUT = config("VIDEO_POLL_TIMEOUT", default=600, cast=int)
VIDEO_POLL_INTERVAL = config("VIDEO_POLL_INTERVAL", default=5, cast=int)

# Circular "facecam" overlay (when a background video is provided).
COMPOSITE_DIAMETER = config("COMPOSITE_DIAMETER", default=320, cast=int)
COMPOSITE_MARGIN = config("COMPOSITE_MARGIN", default=40, cast=int)
# Ring drawn around the circular cutout.
COMPOSITE_BORDER = config("COMPOSITE_BORDER", default=4, cast=int)
# Ring color as "r,g,b" (default white).
COMPOSITE_BORDER_RGB = config("COMPOSITE_BORDER_RGB", default="255,255,255")
